const assert = require('assert');
const fs = require('fs');
const path = require('path');
const engine = require('../../engine');
const { PolicyManager, SECURE_DEFAULT } = require('../../maskit-core/policy-manager');
console.log('Running policy-engine.test.js...');
const validPolicy = { version: '1.0', mode: 'strict', actions: { aws_keys: 'block', github_tokens: 'block', customer_data: 'redact' } };
assert.ok(engine.validatePolicy(validPolicy).ok);
assert.strictEqual(engine.validatePolicy({ mode: 'strict', actions: {} }).ok, false);
assert.strictEqual(engine.validatePolicy({ version: '1.0', mode: 'invalid_mode' }).ok, false);
const temp = path.join(__dirname, 'policy_temp.json');
fs.writeFileSync(temp, JSON.stringify(validPolicy));
const audits = [];
const manager = new PolicyManager(temp, { onAudit: event => audits.push(event) });
assert.strictEqual(manager.getVersion(), '1.0');
assert.strictEqual(manager.validate({ version: '1.0', mode: 'strict', actions: { aws_keys: 'delete' } }).ok, false);
fs.writeFileSync(temp, JSON.stringify({ version: '2.0', mode: 'strict', actions: { aws_keys: 'block' } }));
manager.reload();
assert.strictEqual(manager.getVersion(), '2.0');
fs.writeFileSync(temp, JSON.stringify({ version: '3.0', mode: 'strict', actions: { aws_keys: 'delete' } }));
assert.strictEqual(manager.reload(), false);
assert.deepStrictEqual(manager.getPolicy(), SECURE_DEFAULT);
assert.ok(audits.some(a => a.type === 'policy_fallback'));
fs.unlinkSync(temp); manager.close();
engine.setLocalPolicy(validPolicy);
try { const result = engine.scanText("const key = 'AKIAIOSFODNN7EXAMPLE';"); assert.ok(result.policyDecisions.some(d => d.action === 'block')); } finally { engine.setLocalPolicy(null); }
console.log('policy-engine.test.js passed!');
