const fs = require('fs');
const os = require('os');
const path = require('path');
const config = require('./config');
const { readInventory } = require('./inventory');
function safeEvent(event) { if (!event || typeof event !== 'object') return null; const out = {}; for (const key of ['timestamp','source','application','dataType','confidence','risk','action','contentType','ruleId']) if (event[key] !== undefined) out[key] = event[key]; if (event.policy && typeof event.policy === 'object') out.policy = { name: event.policy.name, version: event.policy.version, result: event.policy.result }; return out; }
function readEvents(days = 30) { const file = path.join(config.getConfigDir(), 'audit.log'); if (!fs.existsSync(file)) return []; const cutoff = Date.now() - days * 86400000; return fs.readFileSync(file, 'utf8').split(/\r?\n/).filter(Boolean).flatMap(line => { try { const event = JSON.parse(line); const time = Date.parse(event.timestamp); return Number.isNaN(time) || time < cutoff ? [] : [safeEvent(event)]; } catch { return []; } }).filter(Boolean); }
function readHealth() { try { const value = JSON.parse(fs.readFileSync(path.join(config.getConfigDir(), 'health.json'), 'utf8')); return { status: String(value.status || 'unknown'), checkedAt: value.checkedAt || null, uptimeSeconds: Number.isFinite(Number(value.uptimeSeconds)) ? Number(value.uptimeSeconds) : null }; } catch { return { status: 'unknown', checkedAt: null, uptimeSeconds: null }; } }
function loadPolicy() { try { return JSON.parse(fs.readFileSync(path.join(__dirname, '../maskit-core/policy.json'), 'utf8')); } catch { return { version: 'unknown', mode: 'unknown' }; } }
function addCount(map, key) { const name = String(key || 'unknown'); map[name] = (map[name] || 0) + 1; }
function summarizeRisk(events) { const weights = { low: 5, medium: 10, high: 25, critical: 50 }; const score = Math.min(100, events.reduce((total, e) => total + (weights[e.risk] || 0), 0)); const level = score >= 50 ? 'critical' : score >= 25 ? 'high' : score >= 10 ? 'medium' : events.length ? 'low' : 'unknown'; const reasons = []; if (events.some(e => e.risk === 'critical')) reasons.push('Critical-risk security events observed'); if (events.some(e => e.action === 'blocked')) reasons.push('Policy blocked one or more events'); if (!events.length) reasons.push('No local evidence events in the selected window'); return { score, level, reasons }; }
function generate(options = {}) { const days = Math.max(1, Number(options.days) || 30); const events = readEvents(days); const policy = loadPolicy(); const inventory = readInventory(config); const byRisk = {}, byAction = {}, bySource = {}; events.forEach(e => { addCount(byRisk, e.risk); addCount(byAction, e.action); addCount(bySource, e.source); }); const risk = summarizeRisk(events); return { schemaVersion: '0.1', generatedAt: new Date().toISOString(), device: { deviceId: process.env.MASKIT_DEVICE_ID || os.hostname(), platform: process.platform }, maskit: { version: '2.4.0' }, policy: { version: String(policy.version || 'unknown'), mode: String(policy.mode || 'unknown'), status: policy.version === 'unknown' ? 'unknown' : 'current' }, aiInventory: inventory, securityEvents: { windowDays: days, total: events.length, byRisk, byAction, bySource }, risk, evidence: { observed: inventory.map(i => `${i.tool} observed on ${i.surface} surface`), calculated: risk.reasons, unknown: ['Whether detected credentials have active permissions', 'Whether sensitive content was submitted outside observed surfaces'] }, agentHealth: readHealth(), privacy: { metadataOnly: true, rawPromptsCollected: false, rawFilesCollected: false, rawClipboardCollected: false, rawSecretsStored: false } }; }
function csv(report) { const rows = [['section','key','value'],['report','generatedAt',report.generatedAt],['report','deviceId',report.device.deviceId],['report','platform',report.device.platform],['policy','version',report.policy.version],['policy','mode',report.policy.mode],['risk','score',report.risk.score],['risk','level',report.risk.level],['securityEvents','total',report.securityEvents.total],['agentHealth','status',report.agentHealth.status]]; report.aiInventory.forEach(i => rows.push(['aiInventory',i.tool,`${i.surface}/${i.status}/${i.lastSeen}`])); Object.entries(report.securityEvents.byRisk).forEach(([k,v]) => rows.push(['byRisk',k,v])); Object.entries(report.securityEvents.byAction).forEach(([k,v]) => rows.push(['byAction',k,v])); return rows.map(row => row.map(value => `"${String(value ?? '').replace(/"/g,'""')}"`).join(',')).join('\n')+'\n'; }
function markdown(report) { const inventory = report.aiInventory.length ? report.aiInventory.map(i => `- ${i.tool} (${i.surface}) · ${i.status} · last seen ${i.lastSeen}`).join('\n') : '- No inventory entries recorded.'; const list = values => values.length ? values.map(v => `- ${v}`).join('\n') : '- None'; return `# MaskIt AI Security Report\n\nGenerated: ${report.generatedAt}\n\n## Device\n- Device: ${report.device.deviceId}\n- Platform: ${report.device.platform}\n- MaskIt version: ${report.maskit.version}\n\n## Policy\n- Version: ${report.policy.version}\n- Mode: ${report.policy.mode}\n- Status: ${report.policy.status}\n\n## AI inventory\n${inventory}\n\n## Security events\n- Window: ${report.securityEvents.windowDays} days\n- Total: ${report.securityEvents.total}\n- By risk: ${JSON.stringify(report.securityEvents.byRisk)}\n- By action: ${JSON.stringify(report.securityEvents.byAction)}\n\n## Agent health\n- Status: ${report.agentHealth.status}\n- Checked at: ${report.agentHealth.checkedAt || 'unknown'}\n\n## Risk\n- Score: ${report.risk.score}/100\n- Level: ${report.risk.level}\n${list(report.risk.reasons)}\n\n## Evidence confidence\n### Observed\n${list(report.evidence.observed)}\n### Calculated\n${list(report.evidence.calculated)}\n### Unknown\n${list(report.evidence.unknown)}\n\n## Privacy guarantees\n- Metadata only: ${report.privacy.metadataOnly}\n- Raw prompts collected: ${report.privacy.rawPromptsCollected}\n- Raw files collected: ${report.privacy.rawFilesCollected}\n- Raw clipboard collected: ${report.privacy.rawClipboardCollected}\n- Raw secrets stored: ${report.privacy.rawSecretsStored}\n`; }
function writeReport(report, outputDir = path.join(process.cwd(),'reports')) { fs.mkdirSync(outputDir,{recursive:true}); fs.writeFileSync(path.join(outputDir,'ai-security-report.json'),JSON.stringify(report,null,2)+'\n'); fs.writeFileSync(path.join(outputDir,'ai-security-report.md'),markdown(report)); fs.writeFileSync(path.join(outputDir,'ai-security-report.csv'),csv(report)); return outputDir; }
module.exports = { generate, writeReport, markdown, csv, readEvents };
