const assert = require("assert");
const fs = require("fs");
const path = require("path");
const engine = require("../engine/index");
const config = require("./config");
let passed = 0; let failed = 0;
function test(name, fn) { try { fn(); passed++; console.log("  PASS  " + name); } catch (err) { failed++; console.error("  FAIL  " + name); console.error("        " + err.message); } }
console.log("\nMaskit MCP server tests\n");
test("config.getConfigPath returns a string", () => { assert.strictEqual(typeof config.getConfigPath(), "string"); });
test("config.getDefaultConfig has expected fields", () => { const defaults = config.getDefaultConfig(); assert.strictEqual(defaults.enabled, true); assert.ok(defaults.severity); assert.ok(defaults.appOverrides); assert.ok(defaults.appOverrides["claude-desktop"]); });
test("config.readConfig returns defaults when no file exists", () => { const cfg = config.readConfig(); assert.strictEqual(cfg.enabled, true); assert.ok(typeof cfg.version === "string"); });
test("config.writeConfig and readConfig round-trip", () => {
  const configPath = config.getConfigPath();
  if (fs.existsSync(configPath)) { try { fs.unlinkSync(configPath); } catch {} }
  const testConfig = config.getDefaultConfig();
  testConfig.testFlag = true;
  const writeResult = config.writeConfig(testConfig);
  assert.strictEqual(writeResult.ok, true);
  const readBack = config.readConfig();
  assert.strictEqual(readBack.testFlag, true);
  delete readBack.testFlag;
  config.writeConfig(readBack);
});
test("config.getSettingsForApp merges app overrides", () => { const settings = config.getSettingsForApp("claude-desktop"); assert.strictEqual(settings.reviewBeforeRedact, true); assert.strictEqual(settings.enabled, true); });
test("config.getSettingsForApp returns base config for unknown app", () => { assert.strictEqual(config.getSettingsForApp("unknown-app").enabled, true); });
test("config.getSettingsForApp returns base config for no app", () => { assert.strictEqual(config.getSettingsForApp().enabled, true); });
test("engine.scanText works via MCP server context", () => { const result = engine.scanText("Contact john@example.com", config.readConfig()); assert.ok(result.findings.length > 0); assert.ok(result.redactedText.includes("***")); });
test("engine.evaluatePolicy works via MCP server context", () => { const result = engine.evaluatePolicy("SSN 123-45-6789", config.readConfig()); assert.ok(result.findings.length > 0); assert.ok(result.riskScore > 0); });
test("engine.getRules works via MCP server context", () => { const rules = engine.getRules(config.readConfig()); assert.ok(rules.rules.length >= 8); assert.ok(rules.rules.some((r) => r.type === "API_KEY")); });
test("engine.updateRules works via MCP server context", () => { const updated = engine.updateRules([{ id: "test-1", name: "Test Rule", pattern: "TEST-\\d{4}", enabled: true }], config.readConfig()); assert.strictEqual(updated.customRules.length, 1); assert.strictEqual(updated.customRules[0].name, "Test Rule"); });
test("engine.getStatus works via MCP server context", () => { const status = engine.getStatus(); assert.strictEqual(status.engineReady, true); assert.ok(status.version); });
test("scan_text handler logic returns JSON", () => { const json = JSON.stringify(engine.scanText("My email is jane@test.com", config.readConfig()), null, 2); assert.ok(json.includes("findings")); assert.ok(json.includes("riskScore")); assert.ok(json.includes("redactedText")); });
test("redact_text handler logic returns redacted text", () => { const settings = config.readConfig(); settings.redactFormat = "stars"; assert.ok(engine.scanText("Card: 4111111111111111", settings).redactedText.includes("***")); });
test("evaluate_policy handler logic returns allowed field", () => { const result = engine.evaluatePolicy("Hello world", config.readConfig()); assert.strictEqual(typeof result.allowed, "boolean"); assert.ok(result.reason); });
test("get_status handler logic returns version", () => { const status = engine.getStatus(); assert.ok(status.version); assert.ok(typeof status.rulesEnabled === "number"); });
test("get_rules handler logic returns rules array", () => { const rules = engine.getRules(config.readConfig()); assert.ok(Array.isArray(rules.rules)); assert.ok(Array.isArray(rules.customRules)); });
test("update_rules handler logic filters invalid patterns", () => { const updated = engine.updateRules([{ id: "1", name: "Valid", pattern: "ID-\\d{3}", enabled: true }, { id: "2", name: "Bad", pattern: "(a+)+", enabled: true }], config.readConfig()); assert.strictEqual(updated.customRules.length, 1); });
test("persistEvents does not throw on first write", () => { const result = engine.scanText("[john@example.com](mailto:john@example.com)", config.readConfig()); assert.ok(result.events.length > 0); assert.doesNotThrow(() => { const logPath = path.join(config.getConfigDir(), "audit-test.log"); if (fs.existsSync(logPath)) fs.unlinkSync(logPath); }); });
test("persistEvents rotation: backup created when log exceeds 10MB", () => { const logPath = path.join(config.getConfigDir(), "audit-rotation-test.log"); const backupPath = logPath + ".1"; if (fs.existsSync(logPath)) fs.unlinkSync(logPath); if (fs.existsSync(backupPath)) fs.unlinkSync(backupPath); fs.mkdirSync(path.dirname(logPath), { recursive: true }); fs.writeFileSync(logPath, Buffer.alloc(11 * 1024 * 1024)); const sizeOver = fs.statSync(logPath).size > 10 * 1024 * 1024; assert.ok(sizeOver, "Test file should be over 10MB"); if (fs.existsSync(backupPath)) fs.unlinkSync(backupPath); if (fs.existsSync(logPath)) fs.unlinkSync(logPath); });
console.log("\n" + passed + " passed, " + failed + " failed\n");
process.exit(failed > 0 ? 1 : 0);
